```{r}
#| label: kmfunc
#| cache: true
#| cache.comments: false
kmfunc <- function(cox, time, event, eventname, xvar, data, rep = FALSE, endfollow = 5) {
  levs <- levels(data %>% pull(!!sym(xvar)))
  nlevs <- length(levs)

  # cox results
  cox <- paste0(
    c("Crude HR (95% CI): ", "Adjusted HR (95% CI): "),
    cox
  )
  cox <- paste0(cox, collapse = "\n")

  fit <- survfit(formula(paste0("Surv(", time, ",", event, "== 'Yes') ~ ", xvar)),
    data = data
  )

  s <- summary(fit, times = seq(0, 365 * endfollow, 1), extend = T)

  plot_data <- tibble(
    "time" = s$time,
    "n.risk" = s$n.risk,
    "n.event" = s$n.event,
    "n.censor" = s$n.censor,
    "estimate" = s$surv,
    "std.error" = s$std.err,
    "strata" = s$strata
  )

  plot_data <- plot_data %>%
    mutate(strata = str_remove_all(strata, paste0(xvar, "=")))

  if (xvar == "sos_com_copd") {
    plot_data <- plot_data %>%
      mutate(
        strata = str_replace(strata, "No", "No COPD"),
        strata = str_replace(strata, "Yes", "COPD")
      )
  }

  annotate_data <- plot_data %>%
    filter(time == 2 * 365)

  p <- ggplot(plot_data, aes(x = time / 365.25, y = 1 - estimate, color = strata)) +
    geom_line(aes(linetype = strata), linewidth = 1) +
    scale_color_brewer(palette = "Set1") +
    scale_x_continuous(breaks = seq(0, endfollow, 1), limits = c(0, endfollow)) +
    scale_y_continuous(labels = scales::label_percent(suffix = ""), limits = c(0, 1)) +
    theme_classic() +
    theme(
      text = element_text(size = 20),
      legend.position = "none"
    ) +
    labs(x = "Follow-up (years)", y = paste0(eventname, " (%)")) +
    ggrepel::geom_text_repel(
      data = annotate_data,
      aes(x = time / 365.25, y = (1 - estimate), label = strata),
      nudge_x = 0, nudge_y = c(-0.2, 0.2), size = 6, hjust = 0
    ) +
    annotate("text", x = 0, y = .95, label = cox, hjust = 0, size = 6)

  # n at risk
  table_data <- plot_data %>%
    filter(
      time %in% c(seq(0, endfollow, 1) * 365)
    )

  t <- ggplot(table_data, aes(y = strata, x = time / 365)) +
    geom_text(aes(label = n.risk), size = 6) +
    scale_x_continuous(breaks = seq(0, endfollow, 1), limits = c(0, endfollow)) +
    coord_cartesian(xlim = c(0, endfollow), clip = "off") +
    labs(subtitle = "No. at risk") +
    theme(
      plot.caption = element_text(size = 20),
      panel.background = element_blank(),
      text = element_text(size = 20),
      axis.text.x = element_blank(),
      axis.ticks = element_blank(),
      axis.title = element_blank(),
      axis.text.y = element_text(hjust = 0, colour = "black")
    )

  km <- (p / t) + plot_layout(height = c(1, .25))
  km
}
```

```{r}
#| label: fig-km-all
#| cache: true
#| cache.comments: false
#| dependson: kmfunc, tbl-outcomes
#| fig-cap: "Cumulative incidence curve for CVD/first HFH"
#| fig-width: 10
#| fig-height: 6

coxinfo <- outall[2:3, 4]
coxinfo <- gsub("\\,.*", "", coxinfo)

kmfunc(
  cox = coxinfo,
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "CVD/HFH",
  xvar = "sos_com_copd",
  data = rsdata
)
```

```{r}
#| label: fig-km-ref
#| cache: true
#| cache.comments: false
#| dependson: kmfunc, fig-outcomes-subgrups, outcomessubfunc
#| fig-cap: "Cumulative incidence curve for CVD/first HFH - HFrEF"
#| fig-width: 10
#| fig-height: 6

mod <- summary(coxph(Surv(sos_outtime_hosphf, sos_out_deathcvhosphf == "Yes") ~ sos_com_copd * relevel(shf_ef_cat, ref = "HFrEF"),
  data = rsdata
))
coxinfo <- c(
  paste0(
    fn(mod$conf.int[1, "exp(coef)"], dig = 2),
    " (", fn(mod$conf.int[1, "lower .95"], dig = 2),
    "-", fn(mod$conf.int[1, "upper .95"], dig = 2), ")"
  ),
  outcomessub %>% filter(level == "  HFrEF") %>% pull(hrcip)
)
coxinfo <- gsub("\\,.*", "", coxinfo)

kmfunc(
  cox = coxinfo,
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "CVD/HFH",
  xvar = "sos_com_copd",
  data = rsdata %>% filter(shf_ef_cat == "HFrEF")
)
```

```{r}
#| label: fig-km-mref
#| cache: true
#| cache.comments: false
#| dependson: kmfunc, fig-outcomes-subgrups, outcomessubfunc
#| fig-cap: "Cumulative incidence curve for CVD/first HFH - HFmrEF"
#| fig-width: 10
#| fig-height: 6

mod <- summary(coxph(Surv(sos_outtime_hosphf, sos_out_deathcvhosphf == "Yes") ~ sos_com_copd * relevel(shf_ef_cat, ref = "HFmrEF"),
  data = rsdata
))
coxinfo <- c(
  paste0(
    fn(mod$conf.int[1, "exp(coef)"], dig = 2),
    " (", fn(mod$conf.int[1, "lower .95"], dig = 2),
    "-", fn(mod$conf.int[1, "upper .95"], dig = 2), ")"
  ),
  outcomessub %>% filter(level == "  HFmrEF") %>% pull(hrcip)
)
coxinfo <- gsub("\\,.*", "", coxinfo)

kmfunc(
  cox = coxinfo,
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "CVD/HFH",
  xvar = "sos_com_copd",
  data = rsdata %>% filter(shf_ef_cat == "HFmrEF")
)
```

```{r}
#| label: fig-km-pef
#| cache: true
#| cache.comments: false
#| dependson: kmfunc, fig-outcomes-subgrups, outcomessubfunc
#| fig-cap: "Cumulative incidence curve for CVD/first HFH - HFpEF"
#| fig-width: 10
#| fig-height: 6

mod <- summary(coxph(Surv(sos_outtime_hosphf, sos_out_deathcvhosphf == "Yes") ~ sos_com_copd * relevel(shf_ef_cat, ref = "HFpEF"),
  data = rsdata
))
coxinfo <- c(
  paste0(
    fn(mod$conf.int[1, "exp(coef)"], dig = 2),
    " (", fn(mod$conf.int[1, "lower .95"], dig = 2),
    "-", fn(mod$conf.int[1, "upper .95"], dig = 2), ")"
  ),
  outcomessub %>% filter(level == "  HFpEF") %>% pull(hrcip)
)
coxinfo <- gsub("\\,.*", "", coxinfo)

kmfunc(
  cox = coxinfo,
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "CVD/HFH",
  xvar = "sos_com_copd",
  data = rsdata %>% filter(shf_ef_cat == "HFpEF")
)
```
